# fly.toml app configuration file generated for tocozwykle on 2025-07-09T21:30:44+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tocozwykle'
primary_region = 'waw'

[build]
  dockerfile = './Dockerfile'

[env]
  APP_ENV = 'production'
  APP_URL = 'https://tocozwykle.fly.dev'
  PORT = '8000'

[processes]
  app = 'deno task server'

[[mounts]]
  source = 'tocozwykle_disk'
  destination = '/app/data'
  processes = ['app']

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
